### ISSUE TITLE
Exception messages in R.curry'd lamdas

### ISSUE THREAD

**Issue by bbozo** [lazebny/ramda-ruby#6]
I.e the `curry -> ` prefix that all exceptions raised from a lamda that's wrapped in a `R.curry` get extra. If you render error messages (for example from client validations) to clients then this `curry ->` is something you need to handle everywhere you add a `R.curry` call, it'll cause issues, it's something to think about

Btw, I'm very excited about this, I'm adopting it on a couple chosen low-intensity controllers in an application I have live <3

**Comment by lazebny** [comment]
Thank you for looking into this. 

Sorry, i haven't a proper issue format yet. But could you share an example which illustrate this issue (what you see and what you expect)? Want to be on the same page.

**Comment by bbozo** [comment]
For example:

```
message is off in {:status=>"declined", :message=>"curry -> client_type must be in set personal, company"}.
--- expected
+++ actual
@@ -1 +1 @@
-"client_type must be in set personal, company"
+"curry -> client_type must be in set personal, company"
```

and this error message is raised in a block of code that I put together to try out how Ramda works, that looks like this:

``` ruby
to_val = R.curry(
  -> (type_klass, key) {
    if type_klass == Integer
      request[key].to_i
    else
      type_klass.new(request[key])
    end
  }
)

v_presence  = -> (key) { validation_error("#{key} must be present") unless request[key].present?; key }
v_inclusion = R.curry(-> (set, key) { validation_error("#{key} must be in set #{set.join(', ')}") unless set.include?(request[key]); key })

ic.set_all(
  # ...
  client_first_name: R.pipe(v_presence, to_val[String])[:client_first_name],
  client_last_name:  R.pipe(v_presence, to_val[String])[:client_last_name],
  # ...
  client_offline_limit: R.pipe(v_presence, to_val[Integer])[:client_offline_limit],
  statement_options: R.pipe(v_presence, method(:validate_statement_options), to_val[String])[:statement_options],
  card_type:         R.pipe(v_presence, v_inclusion[%w(debit credit)], to_val[String])[:card_type],

  status: 'pending',
)
```

where `validation_error` is a method that raises a certain kind of exception (a `ValidationError` exception) which gets rendered:

``` ruby
module Presenter
  class Error
    include Functional
    def call e
      message = e.is_a?(ValidationRaisable::ValidationError) ? e.message : "#{e.class}: #{e.message}"
      # message.gsub!('curry -> ', '') if message.is_a?(String)

      {
        status: 'declined',
        message: message
      }
    end
  end
end
```

(`Functional` here is a mixin which allows you to handle classes with only the `#call` instance method as if they're `Proc`s - much in the same vein as [solnic's](https://github.com/solnic) talk [Blending Functional and OO Programming in Ruby](https://www.youtube.com/watch?v=rMxurF4oqsc), but with a bit more OOP and bit less FP in my case)

---------------------------

Sorry, too much context perhaps ^_^ anyway, I'm kind of a bit new to FP, slowly and carefully wetting my feet for some years now - so take my words with a grain of salt, maybe I do something wrong, or approach the matter in a wrong way.

But still, changing error messages in exceptions seems a bit like meddling into other people's code behavior (ie [Inappropriate Intimacy smell](https://blog.codinghorror.com/code-smells/))

**Comment by lazebny** [comment]
I got you idea and i think it make sense. 

What do you think if ramda will have Ramda.exception_handler? 

Default behavior will be: 
Ramda.exception_handler = -> (e, method_name) { raise e, [method_name, e.exception].join(' -> '), e.backtrace  }

Optional (be able to set in a config):
Ramda.exception_handler = -> (e, method_name) { raise e,  e.exception, e.backtrace  }

**Comment by lazebny** [comment]
I am also not a big expert in FP, just print my idea based on container, how not to raise errors until all validations will be finished. 
``` ruby
class ValueContainer         
  attr_reader :errors, :val

  def initialize(key, val, errors = [])
    @key = val
    @val = val    
    @errors = errors          
  end

  def map(fn)                
    error = fn.call(@key, @val)
    if error.nil?             
      self
    else
      self.class.new(@key, @val, @errors + [error])
    end
  end
end

value_fn = R.curry(-> (key, coerce_fn, request) { ValueContainer.new(key, coerce_fn.call(request[key])) })
coerce_fn = R.curry(-> (type, val) { type == Integer ? val.to_i : type.new(val) })

v_presence = R.map(->(key, val) { "#{key} must be present" unless val.present? } )
v_inclusion = -> (set) { R.map(->(key, val) { "#{key} must be in set #{set.join(', ')}" unless set.include?(val) }) }

options = R.merge(
  R.map(
     -> (fn) { fn.call(request) },
     client_first_name:    R.pipe(value_fn[:client_first_name, coerce_fn[String]], v_presence),
     client_last_name:     R.pipe(value_fn[:client_last_name, coerce_fn[String]], v_presence),
     client_offline_limit: R.pipe(value_fn[:client_offline_limit, coerce_fn[String]], v_presence),
     card_type:            R.pipe(value_fn[:card_type, coerce_fn[String]], v_presence, v_inclusion),
     statement_options:    R.pipe(value_fn[:statement_options, coerce_fn[String]], v_presence, method(:validate_statement_options)),
  ),
  {
    state: 'pending'
  }
)

errors = Ramda.values(options).flat_map(&:errors)

raise(ValidationError, errors) if errors.any?

ic.set_all(Ramda.map(:val.to_proc, options))
```
I didn't test it is just a sketch.

**Comment by lazebny** [comment]
@bbozo 0.8.1 release includes exception handler https://github.com/lazebny/ramda-ruby/commit/e3382fba2a79f9774eeee2dda3b33b6a530c7d31

**Comment by lazebny** [comment]
@bbozo please be free to reopen this issue if you have any suggestions to it.
